config:
  clusters:
    - url: https://alixroden.co.uk:8006/api2/json
      insecure: false
      token_id: "kubernetes-csi@pve!csi"
      token_secret: "7dc221f7-37c9-4eda-b4f0-09d44e5c7a2b"
      region: helsinki
nodeSelector:
  node-role.kubernetes.io/control-plane: "true"
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
storageClass:
  - name: proxmox-data-xfs
    storage: data
    reclaimPolicy: Delete
    fstype: xfs
    cache: writeback
    storageFormat: raw
    ssd: true
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
