apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capacitor-next
  namespace: flux-system
spec:
  interval: 15m
  timeout: 1m
  chartRef:
    kind: OCIRepository
    name: capacitor-next
    namespace: flux-system
  values:
    env:
      AUTH: noauth
      AUTH_DEBUG: "false"
      IMPERSONATE_SA_RULES: "noauth=flux-system:capacitor-next-preset-clusteradmin"
    existingSecret:
      name: capacitor-next
  install:
    createNamespace: true
  releaseName: capacitor-next
  storageNamespace: nfd
  targetNamespace: nfd
