apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    gateway: true
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - ControlPlane:
        icon: kubernetes.png
        description: "Kubernetes Control Plane"
        proxmoxNode: pve
        proxmoxVMID: 100
    - Worker1:
        icon: kubernetes.png
        description: "Kubernetes Worker Node 1"
        proxmoxNode: pve
        proxmoxVMID: 101
    - Worker2:
        icon: kubernetes.png
        description: "Kubernetes Worker Node 2"
        proxmoxNode: pve
        proxmoxVMID: 102
  proxmox.yaml: |
    pve:
      url: "https://alixroden.co.uk:8006"
      token: "a95c3d2e-5ca9-4437-ab81-62ba20ca8b89"
      secret: "kubernetes@pve!ccm"
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "kubernetes"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  docker.yaml: ""
