apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    gateway: true
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: ""
  proxmox.yaml: ""
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "kubernetes"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  docker.yaml: ""
