apiVersion: v1
kind: Secret
metadata:
  name: wg-conf
  namespace: media
stringData:
  wg0.conf: |
    [Interface]
    Address = 10.5.0.2/24
    ListenPort = 51820
    PrivateKey = IIo2HaqHvptf4A/oTupHzz/uaN3J1PkTUynks0YO3VY=
    PostUp = ip rule add to 10.42.0.0/16 lookup main priority 5; ip rule add to 10.43.0.0/16 lookup main priority 5
    PreDown = ip rule del to 10.42.0.0/16 lookup main priority 5; ip rule del to 10.43.0.0/16 lookup main priority 5

    [Peer]
    PublicKey = IEfKWzQ52F81a7WtRp55PuTDHX6O2pAhYNwrapYaxxE=
    AllowedIPs = 0.0.0.0/0, ::/0
    Endpoint = wireguard.alixroden.co.uk:51820
type: Opaque
