pms:
  configStorage: 16Gi
  resources:
    requests:
      gpu.intel.com/xe: "1"
      nextflow.io/fuse: "1"
    limits:
      gpu.intel.com/xe: "1"
      nextflow.io/fuse: "1"
  securityContext:
    privileged: true
  affinity:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
            - key: group
              operator: In
              values:
                - realdebrid
extraInitContainers:
  - name: init-sysctl
    image: busybox:latest
    command:
      - sh
      - -c
      - |
        # Enable IP forwarding inside the pod network namespace
        sysctl -w net.ipv4.ip_forward=1
        sysctl -w net.ipv6.conf.all.forwarding=1
    securityContext:
      privileged: true
extraContainers:
  - image: linuxserver/wireguard:latest
    restartPolicy: Always
    name: wireguard
    env:
      - name: TZ
        value: "Europe/Helsinki"
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
    volumeMounts:
      - name: wg-conf
        mountPath: /etc/wireguard/
        readOnly: false
    securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
          - SYS_MODULE
extraVolumes:
  - name: wg-conf
    secret:
      secretName: wg-conf
  - name: mediamount
    persistentVolumeClaim:
      claimName: media-pvc
  - name: torbox
    persistentVolumeClaim:
      claimName: pvc-torbox
extraVolumeMounts:
  - mountPath: /mnt
    name: mediamount
    mountPropagation: HostToContainer
  - mountPath: /torbox
    name: torbox
    mountPropagation: HostToContainer
extraEnv:
  PLEX_UID: "1000"
  PLEX_GID: "1000"
  PLEX_CLAIM: "claim-CNc19oQfrQXy98s9hnwF"
