apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: infra
spec:
  instances: 2
  ephemeralVolumesSizeLimit:
    shm: 1Gi
  storage:
    size: 16Gi
  postgresql:
    parameters:
      dynamic_shared_memory_type: "sysv"
