apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headlamp
  namespace: kube-system
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Headlamp
    gethomepage.dev/group: Administration
    gethomepage.dev/namespace: kube-system
    gethomepage.dev/app: headlamp
    gethomepage.dev/icon: headlamp.png
    gethomepage.dev/url: "https://headlamp.alixroden.co.uk"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: web
      namespace: infra
      sectionName: websecure-gw
  hostnames:
    - "headlamp.alixroden.co.uk"
  rules:
    - backendRefs:
        - name: headlamp
          port: 80
