---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repo.yaml
  - release.yaml
  - values.yaml
configMapGenerator:
  - name: headlamp-values
    namespace: flux-system
    files:
      - values.yaml
    options:
      labels:
        reconcile.fluxcd.io/watch: "Enabled"
configurations:
  - kustomizeconfig.yaml
generatorOptions:
  disableNameSuffixHash: true
