apiVersion: v1
data:
  values.yaml: |
    config:
      unsafeUseServiceAccountToken: true
      extraArgs:
        - "-unsafe-use-service-account-token"
kind: ConfigMap
metadata:
  labels:
    reconcile.fluxcd.io/watch: Enabled
  name: headlamp-values
  namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: flux-system
spec:
  chart:
    spec:
      chart: headlamp
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      version: 0.42.0
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: headlamp
  storageNamespace: kube-system
  targetNamespace: kube-system
  upgrade:
    disableTakeOwnership: false
    force: true
  valuesFrom:
    - kind: ConfigMap
      name: headlamp-values
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kubernetes-sigs.github.io/headlamp
