apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: headlamp-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: headlamp-admin
  namespace: observability
---
apiVersion: v1
data:
  values.yaml: |
    fullnameOverride: headlamp
    initContainers:
      - # Generate kubeconfig file. Can be removed when https://github.com/kubernetes-sigs/headlamp/issues/1826 is resolved
        command:
          - /bin/sh
          - "-c"
          - |
            kubectl config set-cluster main --server=https://kubernetes.default.svc --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            kubectl config set-credentials main --token=$(cat /tmp/sa-token/token)
            kubectl config set-context main --cluster=main --user=main
            kubectl config use-context main
        env:
          - name: KUBERNETES_SERVICE_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: KUBERNETES_SERVICE_PORT
            value: "6443"
          - name: KUBECONFIG
            value: /home/headlamp/.config/Headlamp/kubeconfigs/config
        image: docker.io/rancher/shell:v7.0.0
        name: create-kubeconfig
        securityContext:
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 100
        volumeMounts:
          - mountPath: /home/headlamp/.config/Headlamp/kubeconfigs
            name: kubeconfig
          - mountPath: /tmp/sa-token
            name: sa-token
            readOnly: true
      - # Install Flux plugin
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:v0.6.0@sha256:055377b9011dcc73235e8969c488ecd92af5cb70aa5d5df0f66c1cea667fdccb
        command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        name: headlamp-plugins
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    clusterRoleBinding:
      create: false
    config:
      pluginsDir: /build/plugins
    podAnnotations:
      reloader.stakater.com/auto: "true"
    service:
      port: 4466
    serviceAccount:
      create: false
      name: headlamp-admin
    volumes:
      - name: headlamp-plugins
        emptyDir: {}
      - name: kubeconfig
        emptyDir: {}
      - name: sa-token
        secret:
          defaultMode: 420
          secretName: headlamp-admin
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
      - mountPath: /home/headlamp/.config/Headlamp/kubeconfigs/config
        name: kubeconfig
        readOnly: true
        subPath: config
kind: ConfigMap
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  labels:
    reconcile.fluxcd.io/watch: Enabled
  name: headlamp-values
  namespace: flux-system
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: headlamp-admin
  name: headlamp-admin
type: kubernetes.io/service-account-token
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./apps/headlamp/headlamp
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      version: 0.42.0
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: headlamp
  storageNamespace: kube-system
  targetNamespace: kube-system
  upgrade:
    disableTakeOwnership: false
    force: true
  valuesFrom:
  - kind: ConfigMap
    name: headlamp-values
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: headlamp
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.42.0
  url: oci://ghcr.io/home-operations/charts-mirror/headlamp
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik.alixroden.co.uk
  name: headlamp
  namespace: kube-system
spec:
  entryPoints:
  - websecure
  ingressClassName: traefik
  routes:
  - kind: Rule
    match: Host(`headlamp.alixroden.co.uk`)
    middlewares:
    - name: traefik-forward-auth
      namespace: traefik
    services:
    - kind: Service
      name: headlamp
      port: 80
  tls:
    secretName: alixroden-co-uk-tls
