apiVersion: v1
data:
  values.yaml: |
    config:
      inCluster: true
      serviceAccountTokenPath: /var/run/secrets/kubernetes.io/serviceaccount/token
      unsafeUseServiceAccountToken: true
kind: ConfigMap
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  labels:
    reconcile.fluxcd.io/watch: Enabled
  name: headlamp-values
  namespace: flux-system
