---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./apps/headlamp/headlamp
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: headlamp-values
  install:
    createNamespace: true
  upgrade:
    disableTakeOwnership: false
    force: true
  interval: 1m0s
  releaseName: headlamp
  storageNamespace: kube-system
  targetNamespace: kube-system
