httproute:
  enabled: true
  parentRefs:
    - kind: Gateway
      name: web
      namespace: infra
      sectionName: websecure-gw
  hostnames:
    - headlamp.alixroden.co.uk
pluginManager:
  enabled: true
config:
  enableHelm: true
