apiVersion: apps/v1
kind: Deployment
metadata:
  name: profilarr
  namespace: media
spec:
  selector:
    matchLabels:
      app: profilarr
  template:
    metadata:
      labels:
        app: profilarr
      namespace: media
    spec:
      containers:
        - name: profilarr
          image: ghcr.io/dictionarry-hub/profilarr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6868
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: ORIGIN
              value: "http://profilarr.alixroden.co.uk"
          volumeMounts:
            - name: profilarr-config
              mountPath: /config
      volumes:
        - name: profilarr-config
          persistentVolumeClaim:
            claimName: profilarr-config-pvc
