apiVersion: v1
kind: Service
metadata:
  name: profilarr
  namespace: media
  labels:
    app: profilarr
spec:
  selector:
    app: profilarr
  ports:
    - port: 9696
      targetPort: 9696
      name: http
