kind: Service
apiVersion: v1
metadata:
  name: webtop
  namespace: infra
spec:
  selector:
    app: webtop
  ports:
    - name: webtop
      port: 3000
      targetPort: 3000
    - name: webtop2
      port: 3001
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtop
  namespace: infra
  labels:
    app: webtop
spec:
  selector:
    matchLabels:
      app: webtop
  replicas: 1
  template:
    metadata:
      labels:
        app: webtop
    spec:
      containers:
        - name: webtop
          image: lscr.io/linuxserver/webtop:alpine-kde
          ports:
            - containerPort: 3000
            - containerPort: 3001
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: AUTO_GPU
              value: "true"
            - name: PIXELFLUX_WAYLAND
              value: "true"
          volumeMounts:
            - name: webtop-config
              mountPath: /config
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /dev/dri/renderD128
              name: renderd128
      volumes:
        - name: webtop-config
          persistentVolumeClaim:
            claimName: webtop-pvc
        - name: dshm
          emptyDir:
            medium: Memory
        - hostPath:
            path: /dev/dri/renderD128
            type: CharDevice
          name: renderd128
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtop-pvc
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: proxmox-data-xfs
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webtop
  namespace: infra
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`webtop.alixroden.co.uk`)
      kind: Rule
      services:
        - name: webtop
          port: 3001
          scheme: https
