---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: "authelia-extauthz-by-gateway"
  namespace: "authelia"
spec:
  targetSelectors:
    - kind: HTTPRoute
      matchLabels:
        security: required
  extAuth:
    headersToExtAuth:
      - "accept"
      - "cookie"
      - "location"
      - "authorization"
      - "proxy-authorization"
      - "x-forwarded-proto"
    failOpen: false
    http:
      backendRefs:
        - name: "authelia"
          namespace: "authelia"
          port: 80
      path: "/api/authz/ext-authz/"
      headersToBackend:
        - Remote-User
        - Remote-Groups
        - Remote-Name
        - Remote-Email
