---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: "authelia-extauthz-by-gateway"
  namespace: "authelia"
spec:
  targetRefs:
    - group: "gateway.networking.k8s.io"
      kind: "HTTPRoute"
      name: "headlamp"
      namespace: "headlamp"
  extAuth:
    headersToExtAuth:
      - "accept"
      - "cookie"
      - "location"
      - "authorization"
      - "proxy-authorization"
      - "x-forwarded-proto"
    failOpen: false
    http:
      backendRefs:
        - name: "authelia"
          namespace: "default"
          port: 80
      path: "/api/authz/ext-authz/"
      headersToBackend:
        - Remote-User
        - Remote-Groups
        - Remote-Name
        - Remote-Email
