apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: keycloak
  namespace: keycloak
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: headlamp
      namespace: headlamp
  oidc:
    provider:
      issuer: "http://auth.alixroden.co.uk/realms/master"
    clientID: "headlamp"
    clientSecret:
      name: keycloak-client-secret
    redirectURL: "https://headlamp.alixroden.co.uk/oauth2/callback"
    logoutPath: "/headlamp/logout"
