apiVersion: v1
kind: Secret
metadata:
  name: crypto
  namespace: authelia
stringData:
  identity_providers.oidc.hmac.key: "yN8VZxDdtDo7Mc27ZBwTqezqki1Z2XzUqeVazPZtdIX5ooKAET44bbumjHGa2sKcv32ieP4uUNh3qLg3cpNxDxJJIt4C1tjVGTGqYCuHM7axqqbgeK8keCkj2ScwJvhZ"
  identity_validation.reset_password.jwt.hmac.key: "Pk85P9scGagTPglknkFD4EUBep5NQsfpIid4N9RAKB3nvc9PJ1nQibExvbPUfEZYcap0Aq1WaA04a3PUmsIXTabs6BHIgsA2iWrkpZuRCkYYSSAf1qTtsBNslnghPE1l"
  session.encryption.key: "Eha4diGZNfeLlJw1atVoQsYT21cnfiGDG3e40cad4fpcNPDWcukrvHYwEKhOMnxhTEFAeicTielIk4HDwlTcW50xQqO5sIwxSaPvHyrSqCdu5DrUoui4vEDJytAo1f7Q"
  storage.encryption.key: "EPieUNx3QY0f3LdYIeDZ8SXLBoSb7CUw3zkwzyeVCB9bCOX63xOPe85yJZvcEL0bgFnqa0v1DpgmkISuCXw9tiEkd7K5uTO6PJhMegq4cC5WIyCIck7hWV5NZBkDh6i7"
