apiVersion: v1
kind: Secret
metadata:
  name: crypto
  namespace: authelia
stringData:
  identity_providers.oidc.hmac.key: "yN8VZxDdtDo7Mc27ZBwTqezqki1Z2XzUqeVazPZtdIX5ooKAET44bbumjHGa2sKcv32ieP4uUNh3qLg3cpNxDxJJIt4C1tjVGTGqYCuHM7axqqbgeK8keCkj2ScwJvhZ"
  identity_validation.reset_password.jwt.hmac.key: "Pk85P9scGagTPglknkFD4EUBep5NQsfpIid4N9RAKB3nvc9PJ1nQibExvbPUfEZYcap0Aq1WaA04a3PUmsIXTabs6BHIgsA2iWrkpZuRCkYYSSAf1qTtsBNslnghPE1l"
  session.encryption.key: "Eha4diGZNfeLlJw1atVoQsYT21cnfiGDG3e40cad4fpcNPDWcukrvHYwEKhOMnxhTEFAeicTielIk4HDwlTcW50xQqO5sIwxSaPvHyrSqCdu5DrUoui4vEDJytAo1f7Q"
  storage.encryption.key: "EPieUNx3QY0f3LdYIeDZ8SXLBoSb7CUw3zkwzyeVCB9bCOX63xOPe85yJZvcEL0bgFnqa0v1DpgmkISuCXw9tiEkd7K5uTO6PJhMegq4cC5WIyCIck7hWV5NZBkDh6i7"
---
apiVersion: v1
kind: Secret
metadata:
  name: users
  namespace: authelia
stringData:
  users.yaml: |
    users:
      alix:
        displayname: Alix Roden
        password: "$argon2id$v=19$m=65536,t=3,p=4$/a7RNLn08FcQkub4FSEjxA$Z8LWVS27/8x+8h6r6OGTGIwA+OoocZLhMcBuug0I2Sc"
        email: alix@roden.me.uk
        groups [ user ]
---
apiVersion: v1
kind: Secret
metadata:
  name: jwk-rsa
  namespace: authelia
stringData:
  private.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCLa2laxCIUyJ9d
    S70qC4bg3z1N1I09W+dgOoXvkWw9gmaZcv3h98WGCVnjuyT/D1fi00IJFy9Afndw
    SRVuXRH+u8i1+G88xcVTty9ShGmJgIg9+YV0pKn9bK05pXHsuBfIAIDvoaanCEvX
    9YByB3P02LBdmhdnMm2+DTudZ3DsmMT9Go0Z1Y2wY9xgkMW4CmZDQsQK/QFmKFtl
    W+P5FL9z1AdgK9iUAyWkWhRWwwB17+2TZ9rRS3eQZA09whbDFQdwDSLWDU9naBSL
    XJgZ+Zft4CgeavSMnSCBVaEAyVIHH2lmZm+ngNkcyjTwRqimcLzVRWIWU9Ko7uii
    NqpvywGrAgMBAAECggEAEoq6fEPRdIoqB7Jm+gyGZ6nI8WzvS9XJM9cUsQPaLWQG
    WSod8cuODYF43vyosvNLcPM/uQ3ITv+CywAtRXxDRGmdC/Z6dM6oq7WVKZhKoOrj
    M7rXsOelY/rsHtqOCDmDkCng+/23uEc2LwaLip7LISkga5Juwl7GkZwY7ZowPobw
    idT8wyf+z90jIpRi3d5UfmBL2sHq5oecOkqF8c1WijMokblEUuLG+emUU+yO1WCx
    jECxs7eLqFHlxVG4ZOqcvAjWxLW0zpsE0oXBW6keiXMLpjB1ag8CLujzKQL32/7D
    0Qfvv0FopEjtIVkQIE+DDSleOAKjfNkofxR6o3WRYQKBgQDAAkzz173pDmqcJP7A
    fXZ2THuS4dihISrFZg0uLyRZL9AHiJ7UNgbuyLDfvS4WIk2yZyynCgTi0IPjYPa5
    UAnq6edIDgKN1OXgWh9BfxE9nf7XFykPVhLolsvWVzxWUwmlk0zZ/SwoICMyfKul
    HCRzLjY3gVi36ZA+b1TJmjy+7QKBgQC54lJH1jgC3CFXvO9+/qAWIDok+FVvpZtn
    pv7QNqJDCKLCBNieCHuDcCVSR40UkIE/2Cnf4cpq7cRCFmCFUR6Qwaql3h2CWy2h
    pKbX6iMl9KpNHXV7ozOB4BuHo2EEqatUOEMItPzu2hDSc2xySc8vUO4r1XR7N8Xl
    DUIqYbWX9wKBgQCI3hr0hoj9JCWigEyH8ecLlKFRpmPBF99hLsmebkQ+vvJPLHfr
    VUfD1pMeKcA8Tt+LmDggKegptfENmATHO+KV7X3LwxDXATeLoTI+gdFMVt9de0jt
    gbGg0j0i4LRF5JMvz7wsd2eOgroUNwIzg8gHwp0rG6yeDIOhvcJ2otdCUQKBgFhd
    mcXitV/Oq98cxzG08/9wtJNsppjbvmPpBEuRHVQGn/DiAuQlninevy89KnkzNO5X
    4Zg3q1Vn0JumLZ5S8NfZ6TjOvXKBy9CDCHmuKaVaiTb9oSL0c4DzO8MgTPe9fOAd
    muhhubgGXGbfTheKtP6GV6Lo52XIHsCDrAefyYcDAoGAXAk3EG+dnGC2OocNDNQe
    zwusyOMn9mB2e9JSDdlf1S68Vxt2Aohue4y2NZeYW0oFDV8h/UzE5RfDoEI+0Aqf
    vMzjoXpi3D0kwVH8xeS9tOTaYTM/Kwb3Gc7xJH5k00XreOBryHE42hsynqkMzUtV
    IokGCS9ApHNjvcPJyXe6wUg=
    -----END PRIVATE KEY-----
