config:
  session:
    cookies:
      - domain: alixroden.co.uk
        authelia_url: "https://auth.alixroden.co.uk"
  access_control:
    default_policy: one_factor
  theme: light

usersDatabase:
  users:
    admin:
      disabled: false
      displayname: "Admin"
      email: "alix@roden.me.uk"
      password: "$argon2id$v=19$m=65536,t=3,p=4$/a7RNLn08FcQkub4FSEjxA$Z8LWVS27/8x+8h6r6OGTGIwA+OoocZLhMcBuug0I2Sc" # replace with your hash
      groups:
        - admins

database:
  type: postgres

postgresql:
  enabled: true
  auth:
    password: "postgresql"

redis:
  enabled: true
  auth:
    password: "postgresql"

gateway:
  enabled: true
  hostnames:
    - "auth.alixroden.co.uk"
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: web
      namespace: infra
      sectionName: websecure-gw

persistence:
  size: 1Gi
  enabled: true
  storageClass: proxmox-data-xfs
  accessModes:
    - ReadWriteOnce
