configMap:
  session:
    cookies: [{ domain: 127.0.0.1 }]
  storage:
    local: { enabled: true }
  notifier:
    filesystem: { enabled: true }
  authentication_backend:
    file: { enabled: true, path: /config/users.yaml }
secret:
  existingSecret: crypto
pod:
  kind: Deployment
  env: [{ name: TZ, value: Europe/Helsinki }]
  extraVolumeMounts:
    - name: users
      mountPath: /config/users.yaml
      subPath: users.yaml
  extraVolumes:
    - name: users
      secret: { secretName: users }
