configMap:
  theme: dark
  session:
    cookies: [{ domain: 127.0.0.1 }]
  notifier:
    filesystem: { enabled: true }
  authentication_backend:
    file: { enabled: true, path: /config/users.yaml }
  storage:
    postgres:
      enabled: true
      deploy: true
      address: tcp://authelia-postgresql:5432
      database: authelia
      username: authelia
      password: { secret_name: db-creds }
  identity_providers:
    oidc:
      enabled: true
      jwks:
        - key_id: default
          algorithm: RS256
          use: sig
          key: { path: /secrets/jwk-rsa/private.pem }
      clients:
        - client_id: public_client
          client_name: Public Test Client
          public: true
          pre_configured_consent_duration: 3 months
          authorization_policy: one_factor
          require_pkce: false
          redirect_uris: [http://localhost:8080/callback]
          claims_policy: legacy
          scopes: [openid, email, profile, groups]
          grant_types: [implicit]
          response_types: [id_token]
          revocation_endpoint_auth_method: none
          introspection_endpoint_auth_method: none
          pushed_authorization_endpoint_auth_method: none
      cors:
        endpoints: [userinfo, authorization, token, revocation, introspection]
        allowed_origins_from_client_redirect_uris: true
      claims_policies:
        legacy:
          id_token:
            [
              email,
              email_verified,
              alt_emails,
              name,
              preferred_username,
              groups,
            ]
secret:
  existingSecret: crypto
  additionalSecrets:
    jwk-rsa:
      items: [{ key: private.pem, path: private.pem }]
    db-creds:
      items: [{ key: password, path: storage.postgres.password.txt }]
pod:
  kind: Deployment
  env: [{ name: TZ, value: Europe/Helsinki }]
  extraVolumeMounts:
    - name: users
      mountPath: /config/users.yaml
      subPath: users.yaml
  extraVolumes:
    - name: users
      secret: { secretName: users }

postgresql:
  auth:
    existingSecret: db-creds
  primary:
    persistence:
      enabled: true
      size: 1Gi
