apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: example-kc
  namespace: keycloak
spec:
  db:
    host: postgres-db.keycloak.svc.cluster.local
    port: 5432
    database: keycloak
    url: jdbc:postgresql://postgres-db.keycloak.svc.cluster.local:5432/keycloak
    schema: public
    passwordSecret:
      key: password
      name: keycloak-db-secret
    usernameSecret:
      key: username
      name: keycloak-db-secret
    vendor: postgres
  ingress:
    enabled: false
  http:
    httpEnabled: true
  instances: 1
  proxy:
    headers: xforwarded
