apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: example-kc
  namespace: keycloak
spec:
  db:
    host: postgresql-db
    passwordSecret:
      key: password
      name: keycloak-db-secret
    usernameSecret:
      key: username
      name: keycloak-db-secret
    vendor: postgres
  hostname:
    hostname: https://keycloak.alixroden.co.uk
    admin: https://keycloak.alixroden.co.uk/admin
    strict: false
    backchannelDynamic: true
  http:
    httpEnabled: true
    httpPort: 8180
    httpsPort: 8543
    tlsSecret: alixroden-co-uk-tls
  instances: 1
  proxy:
    headers: xforwarded
