keycloak:
  hostname: "https://auth.alixroden.co.uk"
  hostnameAdmin: "https://auth.alixroden.co.uk"
  username: "admin"
  password: "KXX14cdup$"
  proxyHeaders: "xforwarded"
  httpEnabled: false
persistence:
  enabled: true
  storageClass: proxmox-data-xfs
  accessMode: ReadWriteOnce
  size: 10Gi
resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"
database:
  jdbcParams: "?prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048"
tls:
  enabled: true
  certManager:
    enabled: true
    issuerRef:
      name: "letsencrypt"
      kind: ClusterIssuer
      namespace: cert-manager
    dnsNames:
      - auth.alixroden.co.uk
extraEnv:
  JAVA_OPTS: "-Xms1024m -Xmx2048m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m"
