keycloak:
  hostname: "https://auth.alixroden.co.uk"
  hostnameAdmin: "https://auth.alixroden.co.uk"
  username: "admin"
  password: "KXX14cdup$"
  proxyHeaders: "xforwarded"
persistence:
  enabled: true
  storageClass: proxmox-data-xfs
  accessMode: ReadWriteOnce
  size: 10Gi
postgres:
  enabled: true
  auth:
    database: "keycloak"
    password: "keycloak-db-password"
