apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
  namespace: traefik
spec:
  selector:
    app: traefik-forward-auth
  ports:
    - name: http
      port: 80
      targetPort: 4181
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: traefik
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      containers:
        - name: traefik-forward-auth
          image: thomseddon/traefik-forward-auth:2
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 4181
            initialDelaySeconds: 10
            periodSeconds: 10
          ports:
            - name: http
              containerPort: 4181
          env:
            - name: CONFIG
              value: "/config"
            - name: SECRET
              value: "VFY0SFhlRDhFQm1HTTdPbHJzOFFLTDdDc0VNTVpudFo="
            - name: AUTH_HOST
              value: "tfa.alixroden.co.uk"
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: traefik-forward-auth.ini
      volumes:
        - name: config
          configMap:
            name: traefik-forward-auth
            items:
              - key: traefik-forward-auth.ini
                path: traefik-forward-auth.ini
