apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
  namespace: traefik
  labels:
    app: traefik-forward-auth
spec:
  selector:
    app: traefik-forward-auth
  ports:
    - name: web
      targetPort: 4181
      port: 4181
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: traefik
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      containers:
        - name: traefik-forward-auth
          image: thomseddon/traefik-forward-auth:2
          env:
            - name: DEFAULT_PROVIDER
              value: oidc
            - name: PROVIDERS_OIDC_ISSUER_URL
              value: https://keycloak.alixroden.co.uk/realms/master
            - name: PROVIDERS_OIDC_CLIENT_ID
              value: traefik-forward-auth
            - name: PROVIDERS_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth
                  key: PROVIDERS_OIDC_CLIENT_SECRET
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth
                  key: SECRET
            - name: INSECURE_COOKIE
              value: "true"
            - name: LOG_LEVEL
              value: debug
          ports:
            - containerPort: 4181
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: traefik-forward-auth
            items:
              - key: traefik-forward-auth.ini
                path: traefik-forward-auth.ini
