---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-forward-auth
  namespace: traefik
data:
  INSECURE_COOKIE: "false"
  COOKIE_DOMAIN: alixroden.co.uk
  DOMAINS: alixroden.co.uk
  AUTH_HOST: tfa.alixroden.co.uk
  DEFAULT_PROVIDER: GENERIC_OUATH
  PROVIDERS_GENERIC_OUATH_ISSUER_URL: https://keycloak.alixroden.co.uk/auth/realms/master
  PROVIDERS_GENERIC_OUATH_CLIENT_ID: traefik-forward-auth
