---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-forward-auth
  namespace: traefik
data:
  traefik-forward-auth.ini: |
    providers.oidc.issuer-url=https://keycloak.alixroden.co.uk/auth/realms/master
    providers.oidc.client-id=traefik-forward-auth
    providers.oidc.client-secret=ntta77UrmyyEOq8Gf
    default-provider=oidc
    cookie-domain=alixroden.co.uk
    secret=9ff492c59c066f53b12e751b89987f51
    auth-host=tfa.alixroden.co.uk
