---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-forward-auth
  namespace: traefik
type: Opaque
data:
  PROVIDERS_OIDC_CLIENT_SECRET: bnR0YTc3VXJteVl5RU9xOEdmUG1hdWl5WWhJcUgwNDY=
  SECRET: VFY0SFhlRDhFQm1HTTdPbHJzOFFLTDdDc0VNTVpudFo=
