apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media
spec:
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
      namespace: media
    spec:
      containers:
        - name: prowlarr
          securityContext:
            privileged: true
          image: linuxserver/prowlarr
          imagePullPolicy: Always
          ports:
            - containerPort: 9696
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc
