policy: sync
provider:
  name: webhook
  webhook:
    image:
      repository: docker.io/hetzner/external-dns-hetzner-webhook
      tag: v0.3.3
    env:
      - name: HETZNER_TOKEN
        valueFrom:
          secretKeyRef:
            name: hetzner
            key: token
sources:
  - traefik-proxy
extraArgs:
  - --default-targets=65.109.107.87
  - --force-default-targets
