apiVersion: v1
data:
  values.yaml: |
    # values.yaml
    ingressRoute:
      dashboard:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: traefik.alixroden.co.uk
        matchRule: Host(`dashboard.alixroden.co.uk`)
        entryPoints:
          - websecure
        ingressClassName: traefik
        middlewares:
          - name: traefik-forward-auth
            namespace: traefik
        tls:
          secretName: alixroden-co-uk-tls
    providers:
      kubernetesGateway:
        enabled: true
      kubernetesCRD:
        allowCrossNamespace: true
kind: ConfigMap
metadata:
  labels:
    reconcile.fluxcd.io/watch: Enabled
  name: traefik-values
  namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 40.2.0
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: traefik
  storageNamespace: traefik
  targetNamespace: traefik
  valuesFrom:
  - kind: ConfigMap
    name: traefik-values
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://traefik.github.io/charts
