---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: "40.2.0"
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: traefik
  storageNamespace: traefik
  targetNamespace: traefik
