# values.yaml
ingressRoute:
  dashboard:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/target: traefik.example.com
    matchRule: Host(`dashboard.alixroden.co.uk`)
    entryPoints:
      - websecure
    ingressClassName: traefik
    tls:
      secretName: alixroden-co-uk-tls
providers:
  kubernetesGateway:
    enabled: true
  kubernetesCRD:
    allowCrossNamespace: true
