apiVersion: helm.toolkit.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: infra
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
      version: '1.*'
    interval: 1h0m0s
    valuesFrom:
    - kind: ConfigMap
      name: external-dns-values
      valuesKey: helm-values.yaml
