apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: media
spec:
  selector:
    matchLabels:
      app: tautulli
  template:
    metadata:
      labels:
        app: tautulli
      namespace: media
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker1
      containers:
        - name: tautulli
          securityContext:
            privileged: true
          image: tautulli/tautulli
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          volumeMounts:
            - name: tautulli-config
              mountPath: /config
          resources:
            requests:
              nextflow.io/fuse: "1"
            limits:
              nextflow.io/fuse: "1"
      volumes:
        - name: tautulli-config
          persistentVolumeClaim:
            claimName: tautulli-config-pvc
