apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: media
  labels:
    app: tautulli
spec:
  selector:
    app: tautulli
  ports:
    - port: 8181
      targetPort: 8181
      name: http
