---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: proxmox-cloud-controller-manager
  namespace: flux-system
spec:
  interval: 1m0s
  type: oci
  url: oci://ghcr.io/sergelogvinov/charts/proxmox-cloud-controller-manager
