apiVersion: v1
kind: Service
metadata:
  name: decypharr
  namespace: media
  labels:
    app: decypharr
spec:
  selector:
    app: decypharr
  ports:
    - port: 8282
      targetPort: 8282
      name: http
