---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-csi-plugin
  namespace: flux-system
spec:
  chart:
    spec:
      chart: proxmox-csi-plugin
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: proxmox-csi-plugin
        namespace: flux-system
      version: "0.18.1"
  valuesFrom:
    - kind: ConfigMap
      name: proxmox-csi-plugin-values
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: proxmox-csi-plugin
  storageNamespace: kube-system
  targetNamespace: kube-system
