# ./apps/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- byparr
- cert-manager
- cert-manager-webhook-hetzner
- comet
- decypharr
- external-dns
- fuse-device-plugin
- headlamp
- homepage
- intel-device-plugins-gpu
- intel-device-plugins-operator
- keycloak
- kubernetes-reflector
- local-path-provisioner
- node-feature-discovery
- pgsql
- plex
- profilarr
- prowlarr
- proxmox-cloud-controller-manager
- proxmox-csi-plugin
- radarr
- seerr
- sonarr
- tautulli
- traefik
- traefik-forward-auth
- zilean
