# ./apps/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - external-dns
  - cert-manager-webhook-hetzner
  - headlamp
  - proxmox-cloud-controller-manager
  - proxmox-csi-plugin
  - node-feature-discovery
  - intel-device-plugins-operator
  - intel-device-plugins-gpu
