apiVersion: v1
kind: Secret
metadata:
  name: hetzner-secret
  namespace: cert-manager
stringData:
  api-token: vrooDFnLLK330ZeXZzIbI93bEPaSP9MZUqBFSW2xZNF7dzO635hZhkWiMPc8a6wIvrooDFnLLK330ZeXZzIbI93bEPaSP9MZUqBFSW2xZNF7dzO635hZhkWiMPc8a6wI
type: Opaque
