apiVersion: apps/v1
kind: Deployment
metadata:
  name: zilean
  namespace: media
spec:
  selector:
    matchLabels:
      app: zilean
  template:
    metadata:
      labels:
        app: zilean
      namespace: media
    spec:
      containers:
        - name: zilean
          image: ghcr.io/thoroslives/zilean:latest

          ports:
            - containerPort: 8181
          env:
            - name: "Zilean__Database__ConnectionString"
              value: "Host=postgresql-rw.default;Database=zilean;Username=app;Password=mCB61TMnLzTYreWdCaEwYQiugNnEJJ79gRdpfoCt2o2yZjP5poLMTTpV2L6N0vFxP;Include Error Detail=true;Timeout=30;CommandTimeout=3600;"
            - name: "GITHUB_TOKEN"
              value: "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"
            - name: "TZ"
              value: "Europe/Helsinki"
          volumeMounts:
            - name: zilean-data
              mountPath: /app/data
            - name: zilean-tmp
              mountPath: /tmp
          tty: true
      volumes:
        - name: zilean-data
          persistentVolumeClaim:
            claimName: zilean-data-pvc
        - name: zilean-tmp
          emptyDir:
            sizeLimit: "1Gi"
            medium: Memory
