apiVersion: apps/v1
kind: Deployment
metadata:
  name: zilean
  namespace: media
spec:
  selector:
    matchLabels:
      app: zilean
  template:
    metadata:
      labels:
        app: zilean
      namespace: media
    spec:
      containers:
        - name: zilean
          image: ghcr.io/thoroslives/zilean:latest

          ports:
            - containerPort: 8181
          env:
            - name: GITHUB_TOKEN
              value: "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"
            - name: TZ
              value: "Europe/Helsinki"
            - name: POSTGRES_DB
              value: zilean
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: host
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: password
          volumeMounts:
            - name: zilean-data
              mountPath: /app/data
            - name: zilean-tmp
              mountPath: /tmp
          tty: true
      volumes:
        - name: zilean-data
          persistentVolumeClaim:
            claimName: zilean-data-pvc
        - name: zilean-tmp
          emptyDir:
            sizeLimit: "1Gi"
            medium: Memory
