apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zilean-data-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: proxmox-data-xfs
