apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: csi.proxmox.sinextra.dev
    volume.kubernetes.io/selected-node: worker1
    volume.kubernetes.io/storage-provisioner: csi.proxmox.sinextra.dev
  name: zilean-data-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: proxmox-data-xfs
  volumeName: pvc-7510f29a-0be1-4a03-91c9-5ae9c031bb84
